//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by LINQ to SQL template for T4 C#
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Data.Linq;


namespace L2SGoodies.Data
{
	public partial class TestDataContext 
	{
		static readonly Func<TestDataContext, System.Int32, Person> compiledPersonFirstOrDefault = CompiledQuery.Compile((TestDataContext dc, System.Int32 _PersonId) => dc.Persons.FirstOrDefault(a=>a.PersonId == _PersonId));
		
		public Person FindPersonById(System.Int32 PersonId) 
		{
			return compiledPersonFirstOrDefault(this, PersonId);
		}

		public Person GetPersonById(System.Int32 PersonId) 
		{
			var result = compiledPersonFirstOrDefault(this, PersonId);
			if (result!=null)
				return result;
			throw new InvalidOperationException("Entity not found in the database.");
		}

	}
}
